### ISSUE TITLE
Cannot start service teamspeak: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/teamspeak/entrypoint.sh\": permission denied": unknown

### ISSUE THREAD

**Issue by sirlattwich** [qdm12/teamspeak-server-alpine#2]
![2020-01-18 17_45_43-Window](https://user-images.githubusercontent.com/26206581/72667864-b055d100-3a20-11ea-84c4-8d3beee37bdc.png)

**Comment by qdm12** [comment]
Let me know if it's fixed, thanks for reporting the issue!

**Comment by sirlattwich** [comment]
Verified working :)
