### ISSUE TITLE
TS3 Server not starting on RPI3 ("syntax error")

### ISSUE THREAD

**Issue by smiley232** [qdm12/teamspeak-server-alpine#3]
Hi,
first of all, I am completely new to using Docker, so if I did something silly I apologize.

I'm using a "Raspberry Pi 3 Model B Rev 1.2" with Raspbian 10 (Buster/Stable), ARMv8, 32bit OS.

I want to run the server on a separat user, so I created the user "teamspeak" (UID=1002) and followed your instructions. "docker build" returns <code>Successfully built 58024242829b</code>, <code>Successfully tagged qmcgaw/teamspeak3-alpine:latest</code>. Directories are created and permissions are set.
Starting the server with (minimal):
<code>docker run --volume "/home/teamspeak/data:/teamspeak/data" --volume "/home/teamspeak/logs:/teamspeak/logs" qmcgaw/teamspeak3-alpine license_accepted=1</code>
leads to <code>./ts3server: line 1: syntax error: unexpected word (expecting ")")</code> and <code>Exit with status 2</code> (regardless of running as "teamspeak" or "root"). The necessary files in ./data were created, though I had to manually set the right user and permissions.
What can I do to resolve this issue?

**Comment by solakram** [comment]
I'm getting exactly the same error on a Raspberry Pi 3 with Raspbian 10 (Buster/Stable)

**Comment by qdm12** [comment]
It's because the ts3server binary program is not compiled for ARM. I'll see what I can do this evening, maybe they have an ARM version (i think it's closed source unfortunately so I can only put the binary there)

**Comment by solakram** [comment]
Oh since in the readme at point 2 is "CLICK IF YOU HAVE AN ARM DEVICE" i thought it will work on raspberry pi. 
i hope you can find a solution for that!

**Comment by qdm12** [comment]
Hi all,

Unfortunately it doesn't seem to be a compiled ARM teamspeak server :cry: (see this [thread](https://forum.teamspeak.com/threads/127389-Can-t-launch-teamspeak-server-on-ARM-CPU/page10), the same error as you). And the Teamspeak source code is indeed closed source, so no way around it.

I'll remove the Readme section for ARM devices, sorry for the confusion!

**Comment by smiley232** [comment]
That's bad news, thanks for the feedback, though.

**Comment by qdm12** [comment]
Still no ARM support, I guess their team will stick to C++ dynamically non cross-compiled builds (a.k.a. ugly builds) for the foreseeable future. I'll close this issue for now as I can't really do much. Sorry for the bad news 😕 !
